### ISSUE TITLE
FileNotFoundError-can not find the .UPF files

### ISSUE THREAD

**Issue by huang-CX** [medford-group/dft-training#3]
Hi,
I want to try to use this project for DFT calculation.
I have installed Atomic Simulation Environment (ASE) and compiled Quantum Espresso 6.7max in my ubuntu16 system. However, when I tried to run the DFT calculation with demo05 [https://github.com/medford-group/dft-training/blob/main/05_Running_DFT_calculation_on_PACE.ipynb](url), I got a file not found error.

****error****
python-BaseException
Traceback (most recent call last):
  File "/home/huang/.local/share/JetBrains/PyCharm2020.3/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/huang/.local/share/JetBrains/PyCharm2020.3/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/huang/project/dft-training/qe_dft_test.py", line 27, in <module>
    print('Energy = {}'.format(image.get_potential_energy()))
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/ase/atoms.py", line 731, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/espresso/espresso.py", line 2412, in get_potential_energy
    self.update(atoms)
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/espresso/espresso.py", line 883, in update
    self.calculate(atoms)
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/espresso/espresso.py", line 829, in calculate
    self.write_input()
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/espresso/espresso.py", line 1477, in write_input
    self.nvalence, self.nel = self.get_nvalence()
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/espresso/espresso.py", line 1256, in get_nvalence
    with open(fname, "r") as fupf:
FileNotFoundError: [Errno 2] No such file or directory: '/home/huang/qe_6.7max/pseudo/O.UPF'

I got a similar error when running demo07, I wonder if these UPF files need to be downloaded separately.
Thanks so much for your help!

**Comment by ajmedford** [comment]
These tutorials are specific to the PACE supercomputing environment at Georgia Tech. If you run them on another system you will indeed need to download the pseudopotentials separately from this website: https://www.materialscloud.org/discover/sssp. That said, note that DFT calculations will run extremely slowly on a typical personal computer, and doing anything beyond these tutorials will likely not be feasible.

**Comment by huang-CX** [comment]
Thanks for your reply. I have downloaded the pseudopotentials but got a new error.

**error**
Connected to pydev debugger (build 203.7148.72)
1st calculation with PBE
# Exception was thrown by pexpect.expect
<pexpect.pty_spawn.spawn object at 0x7ffbcb745250>
command: /home/huang/qe_6.7max/bin/pw.x
args: ['/home/huang/qe_6.7max/bin/pw.x', '-in', 'pw.inp']
buffer (last 100 chars): b' ...\r\n'
before (last 100 chars): b'e3" not allowed\r\n %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\r\n\r\n'
after: b'     stopping'
match: <re.Match object; span=(901, 914), match=b'     stopping'>
match_index: 2
exitstatus: None
flag_eof: False
pid: 28643
child_fd: 25
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.BufferedWriter name=Path('/home/huang/project/dft-training/qe_28583/log')>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
python-BaseException
Traceback (most recent call last):
  File "/home/huang/.local/share/JetBrains/PyCharm2020.3/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/huang/.local/share/JetBrains/PyCharm2020.3/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/huang/project/dft-training/qe_dft_test.py", line 87, in <module>
    dft_training()
  File "/home/huang/project/dft-training/qe_dft_test.py", line 51, in dft_training
    print('Energy = {}'.format(image.get_potential_energy()))
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/ase/atoms.py", line 731, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/espresso/espresso.py", line 2412, in get_potential_energy
    self.update(atoms)
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/espresso/espresso.py", line 883, in update
    self.calculate(atoms)
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/espresso/espresso.py", line 837, in calculate
    self.checkerror()
  File "/home/huang/anaconda3/envs/pyxdh/lib/python3.8/site-packages/espresso/espresso.py", line 2476, in checkerror
    raise RuntimeError(msg.rstrip("\n"))
RuntimeError:      Error in routine  ions_checkin (1):
       ion_dynamics "ase3" not allowed

I would like to ask by the way, is there any way to speed up the DFT calculation. I recently used DFT to calculate the energy of molecular systems, and I need to do a lot of DFT calculations. Thank you again.

**Comment by ajmedford** [comment]
Unfortunately we don't have the resources to provide support for anything other than the infrastructure at Georgia Tech. As for speeding things up, you will definitely need access to a supercomputer if you plan on doing anything beyond a few extremely simple DFT simulations.

**Comment by huang-CX** [comment]
Thanks for your reply. However, the above error seems to be caused by "ase-espresso". I have installed this package following the instructions at this link: https://ase-espresso.readthedocs.io/en/latest/. This makes me very confused.
